export const ROUTES = {
  HOME: "/",
  DASHBOARD: "/dashboard",
  ADMIN_DASHBOARD: "/dashboard/admin",
  ADMIN_NEW_CATEGORY: "/dashboard/admin/categories/new",
  ADMIN_NEW_SUB_CATEGORY: "/dashboard/admin/sub-categories/new",
  ADMIN_CATEGORIES_LIST: "/dashboard/admin/categories",
  ADMIN_SUB_CATEGORIES_LIST: "/dashboard/admin/sub-categories",
  ADMIN_STORES_LIST: "/dashboard/admin/stores",
  ADMIN_ORDERS_LIST: "/dashboard/admin/orders",
  ADMIN_OFFER_TAGS_LIST: "/dashboard/admin/offer-tags",
  ADMIN_COUPONS_LIST: "/dashboard/admin/coupons",

  SELLER_DASHBOARD: "/dashboard/seller",
  SELLER_CREATE_STORE: "/dashboard/seller/stores/new",
  SELLER_STORES_LIST: "/dashboard/seller/stores",
  
  SELLER_HOME: "",
  SELLER_PRODUCTS_LIST: "products",
  SELLER_ORDERS_LIST: "orders",
  SELLER_COUPONS_LIST: "coupons",
  SELLER_INVENTORY_LIST: "inventory",
  SELLER_SHIPPING_LIST: "shipping",
  SELLER_SETTINGS_LIST: "settings",
};
